### ISSUE TITLE
Feature: Install submodules' packages with yarn

### ISSUE THREAD

**Issue by jspantheonlab** [kettek/submodules-install#2]
I faced some issues when install packages inside the submodules by running `yarn`, the submodule packages will install by `npm`. Is there any other way, can install packages by `yarn` ?

- detect the lockfiles in the submodules to determine which packages manager to use
- use the current running package manager to install package in submodule
- default to use `npm`

**Comment by kettek** [comment]
Currently `npm` is hardcoded, however it should be possible to use lockfiles to determine the package manager to use.

It's a bit of a difficult problem, as submodules could be yarn or npm interchangeably, so lock files would probably be the most reliable method before defaulting to npm.

I could also expand the `submodules` field to accept objects in the form of:
```
submodules: [
  {
    path: "my_submodule",
    cmd: "yarn",
    args: ["install"]
  }
]
```

**Comment by jspantheonlab** [comment]
the idea is great, this can handle the other programming language submodule, may add a prop to set the package file.

thanks~

**Comment by kettek** [comment]
I have added support in [v1.1.0](https://github.com/kettek/submodules-install/releases/tag/v1.1.0) for Yarn-based submodules, as well as custom submodules.

The README has been updated with custom submodule syntax.
